name: cached_video_player
description: A new flutter plugin that is virtually a clone of official video_player plugin except that it supports caching( Android and iOS)
version: 1.0.0
homepage: https://github.com/vikram25897/flutter_cached_video_player

flutter:
  plugin:
    platforms:
      android:
        package: com.lazyarts.vikram.cached_video_player
        pluginClass: CachedVideoPlayerPlugin
      ios:
        pluginClass: CachedVideoPlayerPlugin
      web:
        default_package: video_player_web

dependencies:
  meta: ^1.9.0
  video_player_platform_interface: ^6.2.1
  video_player_web: ^2.1.0

  flutter:
    sdk: flutter

dev_dependencies:
  pigeon: ^11.0.1

environment:
  sdk: ">=3.1.0 <4.0.0"
